In [507]:
import numpy as np
from scipy import stats

### Zadanie 4.1

In [508]:
dataset2 = np.array([[1,2,3,4],[1,4,7,10],[14,10,6,2],[10,8,6,4]])
print(dataset2)

[[ 1  2  3  4]
 [ 1  4  7 10]
 [14 10  6  2]
 [10  8  6  4]]


### Zadanie 4.2

In [509]:
dataset2 = np.zeros([4,4])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for vers_idx in range(0, 4):
    for col_idx in range(0,4):
        dataset2[vers_idx, col_idx] = int(first_col_values[vers_idx]+(co_eff[vers_idx]*col_idx))
dataset2

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  7., 10.],
       [14., 10.,  6.,  2.],
       [10.,  8.,  6.,  4.]])

In [510]:
dataset2 = np.zeros([4,4])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for index, values in np.ndenumerate(dataset2):
        dataset2[index[0], index[1]] = int(first_col_values[index[0]]+(co_eff[index[0]]*index[1]))
dataset2

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  7., 10.],
       [14., 10.,  6.,  2.],
       [10.,  8.,  6.,  4.]])

### Zadanie 4.3

In [511]:
#length = int(input("Podaj liczbe kolumn: "))
length = 10
dataset2 = np.zeros([4,length])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for index, values in np.ndenumerate(dataset2):
    dataset2[index[0], index[1]] = int(first_col_values[index[0]]+(co_eff[index[0]]*index[1]))
dataset2


array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.],
       [ 14.,  10.,   6.,   2.,  -2.,  -6., -10., -14., -18., -22.],
       [ 10.,   8.,   6.,   4.,   2.,   0.,  -2.,  -4.,  -6.,  -8.]])

### Zadanie 4.4

In [512]:
for i in np.nditer(dataset2):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.0
4.0
7.0
10.0
13.0
16.0
19.0
22.0
25.0
28.0
14.0
10.0
6.0
2.0
-2.0
-6.0
-10.0
-14.0
-18.0
-22.0
10.0
8.0
6.0
4.0
2.0
0.0
-2.0
-4.0
-6.0
-8.0


### Zadanie 4.5

In [513]:
np.mean(dataset2)
np.median(dataset2)
stats.mode(dataset2)
np.var(dataset2)
np.std(dataset2)
np.max(dataset2) - np.min(dataset2)



50.0

### Zadanie 4.6

In [514]:
np.mean(dataset2, axis=0)
np.median(dataset2, axis=0)
np.median(dataset2, axis=1)


array([ 5.5, 14.5, -4. ,  1. ])

### Zadanie 4.7

In [515]:
dataset1 = np.array([[1,2,3,4], [1,4,7,10], [14,10,6,2], [10,8,6,4]])
dataset1

array([[ 1,  2,  3,  4],
       [ 1,  4,  7, 10],
       [14, 10,  6,  2],
       [10,  8,  6,  4]])

In [516]:
dataset1[0]
dataset1[:, 0]
# dataset1[0:2]
# dataset1[:2, :2]
# dataset1[:, 0:4:2]
# dataset1[:, ::2]
# dataset1[-1]
# dataset1[-1, 1]
# dataset1[-1, 1:]
# dataset1[-1, :1]
# dataset1[-1, :-1]
# dataset1[-1, ::-1] 
# dataset1[::-1]
# dataset1[::-1, ::-1] 
# dataset1[::-1, -1] 
dataset1[:, -3:-1]

array([[ 2,  3],
       [ 4,  7],
       [10,  6],
       [ 8,  6]])

### Zadanie 4.8

In [517]:
dataset2

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.],
       [ 14.,  10.,   6.,   2.,  -2.,  -6., -10., -14., -18., -22.],
       [ 10.,   8.,   6.,   4.,   2.,   0.,  -2.,  -4.,  -6.,  -8.]])

In [518]:
dataset2[:, -1:-3:-1]
dataset2[-1,-1]
dataset2[1::2]
dataset2[0:2, 0:3]
dataset2[:, -2:-3:-1]
dataset2[0, -1]

10.0

### Zadanie 4.9

In [520]:
np.mean(dataset2[-1])
np.median(dataset2[0:2, 0:2])

h_ranges = []
for i in range(0, 4):
    h_ranges.append(np.max(dataset2[i]) - np.min(dataset2[i]))
h_ranges
#np.max(dataset2[0]) - np.min(dataset2[0])

v_ranges = []
for i in range(0, length):
    v_ranges.append(np.max(dataset2[:,i]) - np.min(dataset2[:,i]))
v_ranges

[13.0, 8.0, 4.0, 8.0, 15.0, 22.0, 29.0, 36.0, 43.0, 50.0]

### Zadanie 4.10

In [534]:
dataset2[(dataset2>=3) & (dataset2<6)]
dataset2[dataset2 < 10]
dataset2[((dataset2>2) & (dataset2<4)) | (dataset2 > 10)]

array([ 3., 13., 16., 19., 22., 25., 28., 14.])

### Zadanie 4.11

In [535]:
types3 = [('n1', int), ('n2', int), ('n3', int),
          ('n4', int), ('n5', int)]
values3 = [(1,12,7,14,5), (6,17,3,19,10), (11,12,8,4,1)]
dataset3 = np.array(values3, dtype=types3)
dataset3.dtype = types3


In [547]:
np.sort(dataset3)
np.sort(dataset3, axis=0)
np.sort(dataset3, order='n1', axis=None)[::-1]
np.sort(dataset3, order='n2')
np.sort(dataset3, order=['n2', 'n4'])
print(np.sort(dataset3, order=['n2', 'n4']))

[(11, 12, 8,  4,  1) ( 1, 12, 7, 14,  5) ( 6, 17, 3, 19, 10)]


### Zadanie 4.12

In [551]:
#n_verses = int(input("Podaj liczbę wierszy: "))
n_verses = 10
types3 = [('n1', int), ('n2', int), ('n3', int),
          ('n4', int), ('n5', int)]
dataset3 = np.random.randint(-10, 10, size=(5*n_verses))
dataset3.dtype = types3
print(dataset3)

[( 7, -2, -9,  1,  -6) ( 6, -8,  0, -6,   8) ( 9,  1, -4,  3,  -2)
 (-9,  5,  7, -8, -10) (-5, -1,  2,  5,  -3) ( 6, -6,  3,  2,  -4)
 ( 5,  0,  1,  8,  -7) (-2,  0,  1, -7,  -3) ( 4,  6, -3,  1,   5)
 (-9, -7, -6, -3,  -3)]


### Zadanie 4.13

In [564]:
dataset4 = np.genfromtxt('student-mat.csv', dtype=None, delimiter=',',
    names=True, encoding=None)

np.mean(dataset4['age'])
np.median(dataset4['age'][0:3])
np.sort(dataset4, order=['age'])[-1]

('GP', 'M', 22, 'U', 'GT3', 'T', 3, 1, 'services', 'services', 'other', 'mother', 1, 1, 3, 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 5, 4, 5, 5, 5, 1, 16, 6, 8, 8)