In [67]:
import numpy as np

### Zadanie 4.1

In [68]:
dataset2 = np.array([[1,2,3,4],[1,4,7,10],[14,10,6,2],[10,8,6,4]])
print(dataset2)

[[ 1  2  3  4]
 [ 1  4  7 10]
 [14 10  6  2]
 [10  8  6  4]]


### Zadanie 4.2

In [69]:
dataset2 = np.zeros([4,4])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for vers_idx in range(0, 4):
    for col_idx in range(0,4):
        dataset2[vers_idx, col_idx] = int(first_col_values[vers_idx]+(co_eff[vers_idx]*col_idx))
dataset2

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  7., 10.],
       [14., 10.,  6.,  2.],
       [10.,  8.,  6.,  4.]])

### Zadanie 3