In [67]:
import numpy as np

### Zadanie 4.1

In [68]:
dataset2 = np.array([[1,2,3,4],[1,4,7,10],[14,10,6,2],[10,8,6,4]])
print(dataset2)

[[ 1  2  3  4]
 [ 1  4  7 10]
 [14 10  6  2]
 [10  8  6  4]]


### Zadanie 4.2

In [93]:
dataset2 = np.zeros([4,4])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for vers_idx in range(0, 4):
    for col_idx in range(0,4):
        dataset2[vers_idx, col_idx] = int(first_col_values[vers_idx]+(co_eff[vers_idx]*col_idx))
dataset2

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  7., 10.],
       [14., 10.,  6.,  2.],
       [10.,  8.,  6.,  4.]])

In [95]:
dataset2 = np.zeros([4,4])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for index, values in np.ndenumerate(dataset2):
        dataset2[index[0], index[1]] = int(first_col_values[index[0]]+(co_eff[index[0]]*index[1]))
dataset2

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  7., 10.],
       [14., 10.,  6.,  2.],
       [10.,  8.,  6.,  4.]])

### Zadanie 4.3

In [96]:
#length = int(input("Podaj liczbe kolumn: "))
length = 10
dataset2 = np.zeros([4,length])

first_col_values = [1, 1, 14, 10]
co_eff = [1, 3, -4, -2]

for index, values in np.ndenumerate(dataset2):
    dataset2[index[0], index[1]] = int(first_col_values[index[0]]+(co_eff[index[0]]*index[1]))
dataset2


array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.],
       [ 14.,  10.,   6.,   2.,  -2.,  -6., -10., -14., -18., -22.],
       [ 10.,   8.,   6.,   4.,   2.,   0.,  -2.,  -4.,  -6.,  -8.]])

### Zadanie 4.4

In [76]:
for i in np.nditer(dataset2):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.0
4.0
7.0
10.0
13.0
16.0
19.0
22.0
25.0
28.0
14.0
10.0
6.0
2.0
-2.0
-6.0
-10.0
-14.0
-18.0
-22.0
10.0
8.0
6.0
4.0
2.0
0.0
-2.0
-4.0
-6.0
-8.0
